.TH tickers "May 2023" "user manual"
.SH Name
.PP
tickers - provide company name based on searched stock symbol
.SH Synopsis
make run
.SH Description
.PP
tickers takes a stock symbol as user input and will search and display the symbol and
corresponding company name if found in list of stocks. 
.PP
Stock symbol and name will be written to a .txt file, `search_results.txt`.
.SH License
.SH Author
.PP
WO1 Clayton E. Williams
.PP
clayton.e.williams15.mil@mail.mil
.SH COPYRIGHT
.PP
